#!/bin/bash

echo "This will uninstall hllpp from /usr/local."
read -p "Are you sure? [Y/N]: " confirm

if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
    echo "Uninstall cancelled."
    exit 1
fi

echo "Uninstalling..."

sudo rm -rf /usr/local/include/HLLPP
sudo rm -f /usr/local/lib/libhllpp.a
sudo rm -rf /usr/local/lib/cmake/hllpp
sudo rm -f /usr/local/bin/hllpp_g++
sudo rm -f /usr/local/bin/hllpp_clang++

echo "hllpp uninstalled successfully."